name: DailyJoin
version: ${minecraft.plugin.version}
author: Bergtiger
main: de.bergtiger.dailyjoin.DailyJoin
api-version: 1.16
website: https://github.com/Bergtiger/DailyJoin
softdepend: [TigerList]

commands:
  dailyjoin:
    description: DailyJoin Befehle.
    aliases: [daily]
